<?php

namespace Proxies\__CG__\PoaBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Ttipoparte extends \PoaBundle\Entity\Ttipoparte implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'PoaBundle\\Entity\\Ttipoparte' . "\0" . 'idtipoparte', '' . "\0" . 'PoaBundle\\Entity\\Ttipoparte' . "\0" . 'tipoparte', '' . "\0" . 'PoaBundle\\Entity\\Ttipoparte' . "\0" . 'decumplimiento', '' . "\0" . 'PoaBundle\\Entity\\Ttipoparte' . "\0" . 'hora', '' . "\0" . 'PoaBundle\\Entity\\Ttipoparte' . "\0" . 'horamaxenvio', '' . "\0" . 'PoaBundle\\Entity\\Ttipoparte' . "\0" . 'idmodelo'];
        }

        return ['__isInitialized__', '' . "\0" . 'PoaBundle\\Entity\\Ttipoparte' . "\0" . 'idtipoparte', '' . "\0" . 'PoaBundle\\Entity\\Ttipoparte' . "\0" . 'tipoparte', '' . "\0" . 'PoaBundle\\Entity\\Ttipoparte' . "\0" . 'decumplimiento', '' . "\0" . 'PoaBundle\\Entity\\Ttipoparte' . "\0" . 'hora', '' . "\0" . 'PoaBundle\\Entity\\Ttipoparte' . "\0" . 'horamaxenvio', '' . "\0" . 'PoaBundle\\Entity\\Ttipoparte' . "\0" . 'idmodelo'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Ttipoparte $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdtipoparte()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdtipoparte();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdtipoparte', []);

        return parent::getIdtipoparte();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoparte($tipoparte)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoparte', [$tipoparte]);

        return parent::setTipoparte($tipoparte);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoparte()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoparte', []);

        return parent::getTipoparte();
    }

    /**
     * {@inheritDoc}
     */
    public function setDecumplimiento($decumplimiento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDecumplimiento', [$decumplimiento]);

        return parent::setDecumplimiento($decumplimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function getDecumplimiento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDecumplimiento', []);

        return parent::getDecumplimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function setHora($hora)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHora', [$hora]);

        return parent::setHora($hora);
    }

    /**
     * {@inheritDoc}
     */
    public function getHora()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHora', []);

        return parent::getHora();
    }

    /**
     * {@inheritDoc}
     */
    public function setHoramaxenvio($horamaxenvio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHoramaxenvio', [$horamaxenvio]);

        return parent::setHoramaxenvio($horamaxenvio);
    }

    /**
     * {@inheritDoc}
     */
    public function getHoramaxenvio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHoramaxenvio', []);

        return parent::getHoramaxenvio();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdmodelo(\PoaBundle\Entity\Tmodeloparte $idmodelo = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdmodelo', [$idmodelo]);

        return parent::setIdmodelo($idmodelo);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdmodelo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdmodelo', []);

        return parent::getIdmodelo();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
