<?php

namespace Proxies\__CG__\PoaBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Tpersonas extends \PoaBundle\Entity\Tpersonas implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'PoaBundle\\Entity\\Tpersonas' . "\0" . 'idpersona', '' . "\0" . 'PoaBundle\\Entity\\Tpersonas' . "\0" . 'idestado', '' . "\0" . 'PoaBundle\\Entity\\Tpersonas' . "\0" . 'ci', '' . "\0" . 'PoaBundle\\Entity\\Tpersonas' . "\0" . 'appaterno', '' . "\0" . 'PoaBundle\\Entity\\Tpersonas' . "\0" . 'apmaterno', '' . "\0" . 'PoaBundle\\Entity\\Tpersonas' . "\0" . 'nombre', '' . "\0" . 'PoaBundle\\Entity\\Tpersonas' . "\0" . 'fecnac', '' . "\0" . 'PoaBundle\\Entity\\Tpersonas' . "\0" . 'sexo', '' . "\0" . 'PoaBundle\\Entity\\Tpersonas' . "\0" . 'escivil', '' . "\0" . 'PoaBundle\\Entity\\Tpersonas' . "\0" . 'direccion', '' . "\0" . 'PoaBundle\\Entity\\Tpersonas' . "\0" . 'telefono', '' . "\0" . 'PoaBundle\\Entity\\Tpersonas' . "\0" . 'email', '' . "\0" . 'PoaBundle\\Entity\\Tpersonas' . "\0" . 'codalumno', '' . "\0" . 'PoaBundle\\Entity\\Tpersonas' . "\0" . 'observaciones', '' . "\0" . 'PoaBundle\\Entity\\Tpersonas' . "\0" . 'idarea', '' . "\0" . 'PoaBundle\\Entity\\Tpersonas' . "\0" . 'idsubarea', '' . "\0" . 'PoaBundle\\Entity\\Tpersonas' . "\0" . 'idtipopersona', '' . "\0" . 'PoaBundle\\Entity\\Tpersonas' . "\0" . 'idgrado'];
        }

        return ['__isInitialized__', '' . "\0" . 'PoaBundle\\Entity\\Tpersonas' . "\0" . 'idpersona', '' . "\0" . 'PoaBundle\\Entity\\Tpersonas' . "\0" . 'idestado', '' . "\0" . 'PoaBundle\\Entity\\Tpersonas' . "\0" . 'ci', '' . "\0" . 'PoaBundle\\Entity\\Tpersonas' . "\0" . 'appaterno', '' . "\0" . 'PoaBundle\\Entity\\Tpersonas' . "\0" . 'apmaterno', '' . "\0" . 'PoaBundle\\Entity\\Tpersonas' . "\0" . 'nombre', '' . "\0" . 'PoaBundle\\Entity\\Tpersonas' . "\0" . 'fecnac', '' . "\0" . 'PoaBundle\\Entity\\Tpersonas' . "\0" . 'sexo', '' . "\0" . 'PoaBundle\\Entity\\Tpersonas' . "\0" . 'escivil', '' . "\0" . 'PoaBundle\\Entity\\Tpersonas' . "\0" . 'direccion', '' . "\0" . 'PoaBundle\\Entity\\Tpersonas' . "\0" . 'telefono', '' . "\0" . 'PoaBundle\\Entity\\Tpersonas' . "\0" . 'email', '' . "\0" . 'PoaBundle\\Entity\\Tpersonas' . "\0" . 'codalumno', '' . "\0" . 'PoaBundle\\Entity\\Tpersonas' . "\0" . 'observaciones', '' . "\0" . 'PoaBundle\\Entity\\Tpersonas' . "\0" . 'idarea', '' . "\0" . 'PoaBundle\\Entity\\Tpersonas' . "\0" . 'idsubarea', '' . "\0" . 'PoaBundle\\Entity\\Tpersonas' . "\0" . 'idtipopersona', '' . "\0" . 'PoaBundle\\Entity\\Tpersonas' . "\0" . 'idgrado'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Tpersonas $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdpersona()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdpersona();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdpersona', []);

        return parent::getIdpersona();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdestado($idestado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdestado', [$idestado]);

        return parent::setIdestado($idestado);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdestado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdestado', []);

        return parent::getIdestado();
    }

    /**
     * {@inheritDoc}
     */
    public function setCi($ci)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCi', [$ci]);

        return parent::setCi($ci);
    }

    /**
     * {@inheritDoc}
     */
    public function getCi()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCi', []);

        return parent::getCi();
    }

    /**
     * {@inheritDoc}
     */
    public function setAppaterno($appaterno)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAppaterno', [$appaterno]);

        return parent::setAppaterno($appaterno);
    }

    /**
     * {@inheritDoc}
     */
    public function getAppaterno()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAppaterno', []);

        return parent::getAppaterno();
    }

    /**
     * {@inheritDoc}
     */
    public function setApmaterno($apmaterno)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApmaterno', [$apmaterno]);

        return parent::setApmaterno($apmaterno);
    }

    /**
     * {@inheritDoc}
     */
    public function getApmaterno()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApmaterno', []);

        return parent::getApmaterno();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$nombre]);

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setFecnac($fecnac)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecnac', [$fecnac]);

        return parent::setFecnac($fecnac);
    }

    /**
     * {@inheritDoc}
     */
    public function getFecnac()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecnac', []);

        return parent::getFecnac();
    }

    /**
     * {@inheritDoc}
     */
    public function setSexo($sexo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSexo', [$sexo]);

        return parent::setSexo($sexo);
    }

    /**
     * {@inheritDoc}
     */
    public function getSexo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSexo', []);

        return parent::getSexo();
    }

    /**
     * {@inheritDoc}
     */
    public function setEscivil($escivil)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEscivil', [$escivil]);

        return parent::setEscivil($escivil);
    }

    /**
     * {@inheritDoc}
     */
    public function getEscivil()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEscivil', []);

        return parent::getEscivil();
    }

    /**
     * {@inheritDoc}
     */
    public function setDireccion($direccion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDireccion', [$direccion]);

        return parent::setDireccion($direccion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDireccion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDireccion', []);

        return parent::getDireccion();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefono($telefono)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefono', [$telefono]);

        return parent::setTelefono($telefono);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefono()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefono', []);

        return parent::getTelefono();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodalumno($codalumno)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodalumno', [$codalumno]);

        return parent::setCodalumno($codalumno);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodalumno()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodalumno', []);

        return parent::getCodalumno();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservaciones($observaciones)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservaciones', [$observaciones]);

        return parent::setObservaciones($observaciones);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservaciones()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservaciones', []);

        return parent::getObservaciones();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdarea(\PoaBundle\Entity\Tarea $idarea = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdarea', [$idarea]);

        return parent::setIdarea($idarea);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdarea()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdarea', []);

        return parent::getIdarea();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdsubarea(\PoaBundle\Entity\Tsubareas $idsubarea = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdsubarea', [$idsubarea]);

        return parent::setIdsubarea($idsubarea);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdsubarea()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdsubarea', []);

        return parent::getIdsubarea();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdtipopersona(\PoaBundle\Entity\Ttipopersona $idtipopersona = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdtipopersona', [$idtipopersona]);

        return parent::setIdtipopersona($idtipopersona);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdtipopersona()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdtipopersona', []);

        return parent::getIdtipopersona();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdgrado(\PoaBundle\Entity\Tclgrados $idgrado = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdgrado', [$idgrado]);

        return parent::setIdgrado($idgrado);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdgrado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdgrado', []);

        return parent::getIdgrado();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
