AppBundle\Entity\Tlocacion:
    type: entity
    table: tLocacion
    indexes:
        IDX_4442DDA5975B7D83:
            columns:
                - idunidad
    id:
        idlocacion:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: 'Codigo de Locacion'
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombrelocacion:
            type: string
            nullable: true
            length: 40
            options:
                fixed: false
                comment: 'Nombre de la Locacion'
    manyToOne:
        idunidad:
            targetEntity: Tunidad
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                idunidad:
                    referencedColumnName: idunidad
            orphanRemoval: false
    lifecycleCallbacks: {  }
