AppBundle\Entity\Tsubareas:
    type: entity
    table: Tsubareas
    indexes:
        IDX_8E96863B45BCCC8:
            columns:
                - idarea
    id:
        idsubarea:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: 'Codigo Subarea'
            id: true
            generator:
                strategy: IDENTITY
    fields:
        subarea:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
                comment: 'Nombre de la Subarea'
    manyToOne:
        idarea:
            targetEntity: Tarea
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                idarea:
                    referencedColumnName: idarea
            orphanRemoval: false
    lifecycleCallbacks: {  }
